# -*- coding: utf-8 -*-
"""Trí tuệ nhân tạo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtzdLh8jHhUJCCbY9s2PhtHC7WWeG3ik
"""



with open('text.txt',mode='w') as account:
    account.write('1 Lương Mai Ngọc Lan LT0001 Viện Công nghệ thông minh và tương tác 31241024673 8.5\n')
    account.write('2 Nguyễn Văn B LT0001 Viện Công nghệ thông minh và tương tác 3124XXXXXXX 8.0\n')
    account.write('3 Nguyễn Văn C LT0001 Viện Công nghệ thông minh và tương tác 3124XXXXXXX 7.5')

"""T**rí tuệ nhân tạo**
các kí tự nhập từ bàn phím là string
withopen:('text.txt',mode='w') as account:
thống kê dùng hàm describe
iloc: index location
tìm xe thông tin của một người nào đó: data=data.set_idex(data['Họ và tên']
& và
| hoặc
data['Khoa/Viện'].replace('3I TECH','3I').head(): lệnh thay thế 3itech thành 3i trong bộ nhớ tạm, không thay thế trên file
"""

import pandas as pd
data=pd.read_csv('ds.csv')
data.head(5)
data.tail(3)
data.shape
data.describe()
data.iloc[0:4]
data= data.set_index(data['Họ và tên'])
data.loc['Lương Mai Ngọc Lan']

data[data['Họ và tên']=='Lương Mai Ngọc Lan'].head(5)

data[(data['Lớp']=='LT0001')&(data['Tổ']>1)].head()



data[(data['Lớp']=='LT0001')|(data['Tổ']>1)].head()

data['Khoa/Viện'].replace('3I TECH','3I').head(10)

data['Tổ'].max()

data['Tổ'].min()

data['Tổ'].count()

data['Tổ'].sum()

data['Tổ'].mean()

data['Tổ'].unique()

data.drop(['STT','Khoa/Viện'], axis=1).head()

data=pd.read_csv('ds.csv')
data.drop(data.columns[0:2],axis=1).head(11)

pip install folium

import folium
mymap=folium.Map(location=[10.27333, 105.51833],
                width=950,
                height=550,
                zoom_start=12,
                tiles='openstreetmap')
mymap

import folium
mymap=folium.Map(location=[10.27333, 105.51833],
                width=600,
                height=550,
                zoom_start=12,
                tiles='openstreetmap')
mymap

pip install osmnx

pip install geopandas

place_name='Nha Trang city, Khanh Hoa, Vietnam'

import geopandas as gpd
import osmnx as ox
area = ox.geocode_to_gdf('place_name')
area

import geopandas as gpd
import osmnx as ox
area = ox.geocode_to_gdf('place_name')
area.plot()

from geopy.geocoders import Nominatim
geolocator=Nominatim(user_agent='my-applicatione')
location=geolocator.geocode('Nha Trang Novotel')
print(location.address)

print((location.latitude, location.longitude))
print(location.raw)

from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="my-applicatione")
location = geolocator.reverse("12.2378023, 109.1964739")
print(location.address)

from geopy.distance import geodesic
newport_ri=(41.49038, -71.312796)
cleveland_oh=(41.4999498, -81.695391)
print(geodesic(newport_ri,cleveland_oh).kilometers)



from geopy.distance import great_circle
newport_ri=(41.49038, -71.312796)
cleveland_oh=(41.4999498, -81.695391)
print(great_circle(newport_ri,cleveland_oh).kilometers)

figsize=(20, 11)
world_gdf.plot('pop_density', legend=True, figsize=figsize)



from datetime import date
today=date.today()
print("Currant year: ", today.year)
print("Currant month: ", today.month)
print("Currant day: ", today.day)

import time
localtime=time.localtime(time.time())
print("Local currant time:", localtime)

import calendar
cal=calendar.month(2006,2)
print(cal)

import calendar
cal=calendar.month(2025,4)
print(cal)

calendar.calendar(2025, w=2, l=1, c=3)

calendar.isleap(2025) #coi năm đó có nhuận hay không

calendar.leapdays(2006, 2025)

"""bài tập: deadline tối thứ 2
tìm tên dự án
tìm hiểu dự án cuối kì
"""

pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
#Tao ham lien thuoc inputs
food= ctrl.Antecedent(np.arange(0,10.1,0.1), 'food')
service=ctrl.Antecedent(np.arange(0,10.1,0.1), 'service')
#Tao ham lien thuoc cho output
tip=ctrl.Consequent(np.arange(10,25.1,0.1), 'tip')

food['poor']=fuzz.trimf(food.universe, [0,0,5])
food['average']=fuzz.trimf(food.universe, [0,5,10])
food['good']=fuzz.trimf(food.universe, [5,10,10])
service['poor']=fuzz.trimf(service.universe, [0,0,5])
service['average']=fuzz.trimf(service.universe, [0,5,10])
service['good']=fuzz.trimf(service.universe, [5,10,10])
tip['small']=fuzz.trimf(tip.universe, [10,13.75,17.5])
tip['average']=fuzz.trimf(tip.universe, [13.75,17.5,21.25])
tip['much']=fuzz.trimf(tip.universe, [17.5,21.25,25])

food.view()

"""food.universe: anh xa du lieu"""

service.view()

tip.view()

rule1=ctrl.Rule(food['poor']&service['poor'], tip['small'])
rule2=ctrl.Rule(food['average']&service['poor'], tip['small'])
rule3=ctrl.Rule(food['good']&service['poor'], tip['small'])
rule4=ctrl.Rule(food['poor']&service['average'], tip['small'])
rule5=ctrl.Rule(food['average']&service['average'], tip['average'])
rule6=ctrl.Rule(food['good']&service['average'], tip['much'])
rule7=ctrl.Rule(food['poor']&service['good'], tip['average'])
rule8=ctrl.Rule(food['average']&service['good'], tip['much'])
rule9=ctrl.Rule(food['good']&service['good'], tip['much'])

#Mo phong va dieu khien
tipping_ctrl=ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])
tipping=ctrl.ControlSystemSimulation(tipping_ctrl)
#Danh gia va kiem tra lai
tipping.input['food']=0
tipping.input['service']=0
#Xac dinh gia tru dieu khien
tipping.compute()
print(tipping.output['tip'])
tip.view(sim=tipping)

#May dieu hoa
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
temperature=ctrl.Antecedent(np.arange(0, 41, 1), 'temperature')
humidity=ctrl.Antecedent(np.arange(0, 101, 1), 'humidity')
fan_speed=ctrl.Consequent(np.arange(0, 101, 1), 'fan_speed')#do phan giai thap to do xu li nhanh(dpg:1)
temperature['cold']=fuzz.trimf(temperature.universe, [0, 0, 20])
temperature['warm']=fuzz.trimf(temperature.universe, [15, 25, 40])
temperature['hot']=fuzz.trimf(temperature.universe, [30, 40, 40])
humidity['dry']=fuzz.trimf(humidity.universe, [0, 0, 50])
humidity['normal']=fuzz.trimf(humidity.universe, [30, 50, 70])
humidity['wet']=fuzz.trimf(humidity.universe, [50, 100, 100])
fan_speed['low']=fuzz.trimf(fan_speed.universe, [0, 0, 50])
fan_speed['medium']=fuzz.trimf(fan_speed.universe, [30, 50, 70])
fan_speed['high']=fuzz.trimf(fan_speed.universe, [50, 100, 100])

temperature.view()

humidity.view()

fan_speed.view()

rule1=ctrl.Rule(temperature['cold']&humidity['dry'], fan_speed['low'])
rule2=ctrl.Rule(temperature['cold']&humidity['normal'], fan_speed['low'])
rule3=ctrl.Rule(temperature['cold']&humidity['wet'], fan_speed['medium'])
rule4=ctrl.Rule(temperature['warm']&humidity['dry'], fan_speed['low'])
rule5=ctrl.Rule(temperature['warm']&humidity['normal'], fan_speed['medium'])
rule6=ctrl.Rule(temperature['warm']&humidity['wet'], fan_speed['high'])
rule7=ctrl.Rule(temperature['hot']&humidity['dry'], fan_speed['medium'])
rule8=ctrl.Rule(temperature['hot']&humidity['normal'], fan_speed['high'])
rule9=ctrl.Rule(temperature['hot']&humidity['wet'], fan_speed['high'])

fan_speed_ctrl=ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])
fan_speed_simulation=ctrl.ControlSystemSimulation(fan_speed_ctrl)
fan_speed_simulation.input['temperature']=15
fan_speed_simulation.input['humidity']=40
fan_speed_simulation.compute()
print(f"Fan Speed: {fan_speed_simulation.output['fan_speed']}")
temperature.view(sim=fan_speed_simulation)
humidity.view(sim=fan_speed_simulation)
fan_speed.view(sim=fan_speed_simulation)

"""ham tam giac: trimf
ham gauss:
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
#Inputs
traffic_condition=ctrl.Antecedent(np.arange(0, 11, 1), 'traffic')
distance_to_customer=ctrl.Antecedent(np.arange(0, 16, 1), 'distance')
weather_condition=ctrl.Antecedent(np.arange(0, 3, 1), 'weather')
order_preparation_time=ctrl.Antecedent(np.arange(0, 16, 1), 'time')
driver_fatigue_level=ctrl.Antecedent(np.arange(0, 11, 1), 'fatigue')
#Outputs
estimated_delivery_time=ctrl.Consequent(np.arange(0, 26, 1), 'delivery_time')
incentive_bonus=ctrl.Consequent(np.arange(0, 21, 1), 'incentive')
driver_performance_rating=ctrl.Consequent(np.arange(0, 6, 0.1), 'rating')
#dulieu dau vao
traffic_condition['good']=fuzz.trimf(traffic_condition.universe, [0, 0, 5])
traffic_condition['normal']=fuzz.trimf(traffic_condition.universe, [0, 5, 10])
traffic_condition['bad']=fuzz.trimf(traffic_condition.universe, [5, 10, 10])
distance_to_customer['short']=fuzz.trimf(distance_to_customer.universe, [0, 0, 7])
distance_to_customer['normal']=fuzz.trimf(distance_to_customer.universe, [0, 8, 15])
distance_to_customer['large']=fuzz.trimf(distance_to_customer.universe, [7, 15, 15])
weather_condition['good']=fuzz.trimf(weather_condition.universe, [0, 0, 1])
weather_condition['normal']=fuzz.trimf(weather_condition.universe, [0, 1, 2])
weather_condition['bad']=fuzz.trimf(weather_condition.universe, [1, 2, 2])
order_preparation_time['fast']=fuzz.trimf(order_preparation_time.universe, [0, 0, 5])
order_preparation_time['normal']=fuzz.trimf(order_preparation_time.universe, [0, 5, 10])
order_preparation_time['slow']=fuzz.trimf(order_preparation_time.universe, [5, 10, 15])
driver_fatigue_level['good']=fuzz.trimf(driver_fatigue_level.universe, [0, 0, 5])
driver_fatigue_level['normal']=fuzz.trimf(driver_fatigue_level.universe, [0, 5, 10])
driver_fatigue_level['bad']=fuzz.trimf(driver_fatigue_level.universe, [5, 10, 10])
estimated_delivery_time['fast']=fuzz.trimf(estimated_delivery_time.universe, [0, 5, 10])
estimated_delivery_time['normal']=fuzz.trimf(estimated_delivery_time.universe, [5, 10, 15])
estimated_delivery_time['slow']=fuzz.trimf(estimated_delivery_time.universe, [10, 15, 25])
incentive_bonus['small']=fuzz.trimf(incentive_bonus.universe, [0, 5, 10])
incentive_bonus['normal']=fuzz.trimf(incentive_bonus.universe, [5, 10, 15])
incentive_bonus['large']=fuzz.trimf(incentive_bonus.universe, [10, 15, 20])
driver_performance_rating['good']=fuzz.trimf(driver_performance_rating.universe, [0, 0, 3])
driver_performance_rating['normal']=fuzz.trimf(driver_performance_rating.universe, [2, 3, 4])
driver_performance_rating['bad']=fuzz.trimf(driver_performance_rating.universe, [3, 5, 5])

traffic_condition.view()

distance_to_customer.view()

weather_condition.view()

order_preparation_time.view()

driver_fatigue_level.view()

estimated_delivery_time.view()

incentive_bonus.view()

driver_performance_rating.view()

#giao thong+ khoang cach
rule1=ctrl.Rule(traffic_condition['good']&distance_to_customer['short'], estimated_delivery_time['fast'])
rule2=ctrl.Rule(traffic_condition['normal']&distance_to_customer['normal'], estimated_delivery_time['normal'])
rule3=ctrl.Rule(traffic_condition['bad']&distance_to_customer['large'], estimated_delivery_time['slow'])
#thoi tiet va tien thuong khuyen khich
rule4=ctrl.Rule(weather_condition['good'], incentive_bonus['small'])
rule5=ctrl.Rule(weather_condition['normal'], incentive_bonus['normal'])
rule6=ctrl.Rule(weather_condition['bad'], incentive_bonus['large'])
#thoi gian cb don hang va giao hang
rule7=ctrl.Rule(order_preparation_time['fast']&traffic_condition['good'], estimated_delivery_time['fast'])
rule8=ctrl.Rule(order_preparation_time['normal']&traffic_condition['normal'], estimated_delivery_time['normal'])
rule9=ctrl.Rule(order_preparation_time['slow']&traffic_condition['bad'], estimated_delivery_time['slow'])
#do met moi cua tai xe va xep hang hieu xuat
rule10=ctrl.Rule(driver_fatigue_level['good'], driver_performance_rating['good'])
rule11=ctrl.Rule(driver_fatigue_level['normal'], driver_performance_rating['normal'])
rule12=ctrl.Rule(driver_fatigue_level['bad'], driver_performance_rating['bad'])
#luat ket hop nhieu yeu to
rule13=ctrl.Rule(distance_to_customer['large']&traffic_condition['bad'], estimated_delivery_time['slow'], incentive_bonus['large'])
rule14=ctrl.Rule(distance_to_customer['short']&traffic_condition['good'], estimated_delivery_time['fast'], incentive_bonus['small'])
rule15=ctrl.Rule(driver_fatigue_level['bad']&traffic_condition['bad'], driver_performance_rating['bad'], estimated_delivery_time['slow'])
#them luat

control_system=ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15])
fuzzy_system=ctrl.ControlSystemSimulation(control_system)
fuzzy_system.input['traffic']=7
fuzzy_system.input['distance']=9
fuzzy_system.input['weather']=2
fuzzy_system.input['time']=10
fuzzy_system.input['fatigue']=8
fuzzy_system.compute()
print("Thời gian dự kiến:", fuzzy_system.output['delivery_time'])
print("Thưởng:", fuzzy_system.output['incentive'])
print("Đánh giá:", fuzzy_system.output['rating'])
estimated_delivery_time.view(sim=fuzzy_system)
incentive_bonus.view(sim=fuzzy_system)
driver_performance_rating.view(sim=fuzzy_system)

